### PR TITLE
Slight reworking of temperature-dependent cross sections

### PR DESCRIPTION
**Pull request by paulromano**

### CODE REVIEW

**Comment by paulromano** [comment]
You'll have to generate a new library since this makes probability tables temperature-dependent.

**Comment by nelsonag** [comment]
Is now a good time to update the Dropbox/box link?

**Comment by paulromano** [comment]
Sure- I'll put a new version in my box account and make the change on this PR.

**Comment by paulromano** [comment]
I added a link to the new data;  the test failure is just due to it picking up the previous version from cache.

**Pull request merged**
